// Website CMS: what can be edited on the public website, and the defaults.
// Pure code (no database), safe for client components.
//
// The home page template (lib/site/template.ts, generated by
// 06-Website/site-src/build.ps1) carries these markers, filled by render.ts:
//   <!--f:key-->default text<!--/f-->        editable text (key = "section.name")
//   <!--section:key-->…<!--/section:key-->   removed when the section is switched off
//   <!--if:flag-->…<!--/if:flag-->           only when a feature is on
//   <!--ifnot:flag-->…<!--/ifnot:flag-->     only when it's off
//   <!--block:services-->…                   the services and prices grid
//   <!--seo-->…<!--/seo-->, <!--analytics-->  head tags and tracking
//   {{TOKEN}}                                business details

export type SiteFlags = { pickup: boolean };
export const DEFAULT_FLAGS: SiteFlags = { pickup: false };

export const FLAG_INFO: { key: keyof SiteFlags; label: string; help: string }[] = [
  {
    key: "pickup",
    label: "Pickup & delivery",
    help:
      "Shows pickup booking everywhere: the website (Book a pickup buttons, pickup text, the Book section), the Club app booking page and the WhatsApp bot (booking in the chat). When off, the website talks about dropping off at the store instead.",
  },
];

export const SECTIONS: { key: string; label: string; help?: string; pickupOnly?: boolean }[] = [
  { key: "hero", label: "Top banner", help: "Headline, buttons and the order-tracking card" },
  { key: "rating", label: "Google rating badge", help: "The ★ 4.9 on Google line in the top banner" },
  { key: "promise", label: "Promise strip", help: "The four icons under the banner" },
  { key: "services", label: "Services & prices" },
  { key: "how", label: "How it works" },
  { key: "club", label: "London Wash Club" },
  { key: "book", label: "Book a pickup", help: "Shown only while Pickup & delivery is on", pickupOnly: true },
  { key: "contact", label: "Visit us / contact" },
  { key: "map", label: "Google map", help: "The map next to the contact details" },
  { key: "wa_float", label: "Floating WhatsApp button", help: "The green button in the corner" },
];
export const sectionDefaults = (): Record<string, boolean> => Object.fromEntries(SECTIONS.map((s) => [s.key, true]));

export type Business = {
  phone: string;
  whatsapp: string; // digits with country code
  email: string;
  address: string; // lines separated by new lines
  hours: string; // lines separated by new lines
  hours_short: string;
  map_link: string;
  review_link: string;
  instagram_url: string;
  instagram_handle: string;
  facebook_url: string;
  latitude: string;
  longitude: string;
  street: string;
  city: string;
  postcode: string;
};
export const DEFAULT_BUSINESS: Business = {
  phone: "+91 85900 00868",
  whatsapp: "918590000868",
  email: "hello@thelondonwash.com",
  address: "Near Kerala PSC Office, Thazhe\nVettipuram, Pathanamthitta\nKerala 689645",
  hours: "Monday – Saturday: 9 AM – 9 PM\nSunday: 11 AM – 6 PM",
  hours_short: "Mon – Sat 9 AM – 9 PM · Sun 11 AM – 6 PM",
  map_link: "https://maps.app.goo.gl/ao1QecaaEpGTqgj58",
  review_link: "https://g.page/r/CTraiq6EbHBIEBM/review",
  instagram_url: "https://www.instagram.com/thelondonwash.in/",
  instagram_handle: "@thelondonwash.in",
  facebook_url: "https://www.facebook.com/thelondonwash",
  latitude: "9.2729487",
  longitude: "76.79011",
  street: "Near Kerala PSC Office, Thazhe, Vettipuram",
  city: "Pathanamthitta",
  postcode: "689645",
};
export const BUSINESS_FIELDS: { key: keyof Business; label: string; multiline?: boolean; help?: string }[] = [
  { key: "phone", label: "Phone (as shown)" },
  { key: "whatsapp", label: "WhatsApp number", help: "Digits with country code, e.g. 918590000868" },
  { key: "email", label: "Email" },
  { key: "address", label: "Address (as shown)", multiline: true },
  { key: "hours", label: "Opening hours (contact section)", multiline: true },
  { key: "hours_short", label: "Opening hours (footer, one line)" },
  { key: "map_link", label: "Google Maps link" },
  { key: "review_link", label: "Google review link" },
  { key: "instagram_url", label: "Instagram link" },
  { key: "instagram_handle", label: "Instagram name" },
  { key: "facebook_url", label: "Facebook link" },
  { key: "street", label: "Street (for Google)", help: "Used in the business details Google reads" },
  { key: "city", label: "Town / city (for Google)" },
  { key: "postcode", label: "PIN code (for Google)" },
  { key: "latitude", label: "Store latitude", help: "Map pin, also used for the pickup area" },
  { key: "longitude", label: "Store longitude" },
];

export type ServiceItem = { title: string; text: string; price: number; unit: string; icon: string; hidden?: boolean };
export const SERVICE_UNITS = ["piece", "kg", "pair", "set", "item", "sq ft"];

export type Seo = {
  title: string;
  description: string;
  keywords: string; // focus keywords, comma separated (for the checklist; not shown to Google)
  canonical: string;
  og_title: string;
  og_description: string;
  og_image: string;
  indexing: boolean; // let Google show the site
  google_verification: string;
  bing_verification: string;
  ga_id: string; // Google Analytics 4 measurement id (G-XXXX)
  gtm_id: string; // Google Tag Manager container id (GTM-XXXX), optional
  local_business: boolean; // add the business details Google reads (schema.org)
};
export const DEFAULT_SEO: Seo = {
  title: "The London Wash | Laundry & dry cleaning in Pathanamthitta",
  description:
    "The London Wash, the art of laundry. Dry cleaning, wash & iron, steam ironing, shoe, blanket and specialist cleaning in Pathanamthitta. Rated 4.9 on Google. Call or WhatsApp +91 85900 00868.",
  keywords: "laundry Pathanamthitta, dry cleaning Pathanamthitta, laundry near me",
  canonical: "https://www.thelondonwash.com/",
  og_title: "The London Wash: the art of laundry",
  og_description: "Laundry and dry cleaning in Pathanamthitta. Rated 4.9 on Google.",
  og_image: "https://www.thelondonwash.com/site/assets/og.png",
  indexing: true,
  google_verification: "",
  bing_verification: "",
  ga_id: "",
  gtm_id: "",
  local_business: true,
};

// Pickup booking (WhatsApp chat and Club app). Used only while the Pickup & delivery switch is on.
export type PickupWindow = { start: string; end: string }; // "09:00"
export type PickupConfig = {
  radius_km: number;
  capacity: number; // pickups per time window
  days_ahead: number; // how many days customers can book
  lead_minutes: number; // earliest booking from now
  weekday_windows: PickupWindow[]; // Monday–Saturday
  sunday_windows: PickupWindow[];
};
export const DEFAULT_PICKUP: PickupConfig = {
  radius_km: 30,
  capacity: 2,
  days_ahead: 3,
  lead_minutes: 90,
  weekday_windows: [
    { start: "09:00", end: "11:00" },
    { start: "11:00", end: "13:00" },
    { start: "14:00", end: "16:00" },
    { start: "16:00", end: "18:00" },
    { start: "18:00", end: "20:00" },
  ],
  sunday_windows: [
    { start: "11:00", end: "13:00" },
    { start: "14:00", end: "16:00" },
  ],
};

// Editable texts, grouped like the page. Labels for the keys in the template.
export const FIELD_GROUPS: { key: string; label: string }[] = [
  { key: "hero", label: "Top banner" },
  { key: "promise", label: "Promise strip" },
  { key: "services", label: "Services & prices (headings)" },
  { key: "how", label: "How it works" },
  { key: "club", label: "London Wash Club" },
  { key: "book", label: "Book a pickup (pickup only)" },
  { key: "contact", label: "Visit us" },
  { key: "footer", label: "Footer" },
];
const LABELS: Record<string, string> = {
  eyebrow: "Small heading",
  title: "Heading",
  lead: "Intro text",
  lead_pickup: "Intro text (pickup on)",
  lead_store: "Intro text (pickup off)",
  rating_score: "Google rating",
  rating_count: "Number of reviews",
  trust_pickup: "Point 1 (pickup on)",
  trust_store: "Point 1 (pickup off)",
  trust_2: "Point 2",
  trust_3: "Point 3",
  pickup_title: "Box 1 heading (pickup on)",
  pickup_text: "Box 1 text (pickup on)",
  store_title: "Box 1 heading (pickup off)",
  store_text: "Box 1 text (pickup off)",
  note: "Note under the prices",
  text: "Text",
  cta_note: "Text under the app button",
  review_note: "Review note",
  about_pickup: "About text (pickup on)",
  about_store: "About text (pickup off)",
  copyright: "Copyright line",
};
export function fieldLabel(key: string) {
  const name = key.split(".").slice(1).join(".");
  if (LABELS[name]) return LABELS[name];
  let m = name.match(/^(\d)_(title|text)$/);
  if (m) return `Box ${m[1]} ${m[2] === "title" ? "heading" : "text"}`;
  m = name.match(/^([ps])(\d)_(title|text)$/);
  if (m) return `Step ${m[2]} ${m[3] === "title" ? "heading" : "text"} (pickup ${m[1] === "p" ? "on" : "off"})`;
  m = name.match(/^perk(\d)_(title|text)$/);
  if (m) return `Perk ${m[1]} ${m[2] === "title" ? "word" : "text"}`;
  return name.replace(/_/g, " ");
}

/** Text as typed in the CMS → safe HTML. *word* becomes the accent (italic) style. */
export function liteToHtml(s: string) {
  return esc(s).replace(/\*([^*\n]+)\*/g, "<em>$1</em>");
}
/** Default HTML from the template → text for the CMS editor. */
export function htmlToLite(s: string) {
  return s
    .replace(/<em>([\s\S]*?)<\/em>/g, "*$1*")
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
}
export function esc(s: string) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

/** Editable fields and their default text, read from the template markers. */
export function fieldDefaults(template: string): { key: string; group: string; def: string }[] {
  const seen = new Set<string>();
  const out: { key: string; group: string; def: string }[] = [];
  for (const m of template.matchAll(/<!--f:([\w.]+)-->([\s\S]*?)<!--\/f-->/g)) {
    if (seen.has(m[1])) continue;
    seen.add(m[1]);
    out.push({ key: m[1], group: m[1].split(".")[0], def: htmlToLite(m[2]) });
  }
  return out;
}

export const WA_TEXT = { pickup: "Hi The London Wash, I would like to book a pickup.", general: "Hi The London Wash, I have a question.", quote: "Hi The London Wash, can I get a price for this?" };
